all:
  hosts:
    dev:
      ansible_host: localhost
      ansible_connection: local
    longer:
      ansible_host: s-medgen-longer.charite.de
      host_url: s-medgen-longer.charite.de
    freescout:
      ansible_host: s-c17-wmg-app01.charite.de
      host_url: freescout.charite.de
    phenotips:
      ansible_host: s-bcrt-webdb01.charite.de
      host_url: phenotips.charite.de
