- name: Setup development computer
  hosts: dev
  roles:
    - common
  tasks:
    - name: Install ansible required packages
      become: true
      apt:
        pkg:
          - sshpass
        state: latest
        update_cache: true
