- name: Set deploy directory permissions
  become: true
  hosts: all
  tasks:
- name: Freescout
  hosts: freescout
  tasks:
    - name: Ensure git repository exists
      ansible.builtin.git:
        repo: https://{{github_user}}:{{github_token}}@github.com/xiamaz/freescout-charite.git
        dest: "{{ deploy_root}}/freescout"
          # - name: Freescout
          #   hosts: freescout
          # - name: webrelay
          #   hosts: phenotips
          # - name: cads_data_exchange
          #   hosts: phenotips
