- name: Setup clinical report templating
  hosts:
    - phenotips
  tags: clinical_report_templating
  vars:
    application_name: "{{ dir_clinical_report_templating }}"
    branch_name: include_certificates
  tasks:
    - name: Download repository
      become: yes
      become_user: "{{ run_user }}"
      ansible.builtin.git:
        # repo: https://{{github_user}}:{{github_token}}@github.com/xiamaz/clinical-report-templating.git
        repo: https://github.com/KuechlerO/clinical-report-templating
        dest: "{{ deploy_root}}/{{ application_name }}"
        version: "{{ branch_name }}"

    - name: Place env configuration
      become: yes
      become_user: "{{ run_user }}"
      template:
        dest: "{{ deploy_root }}/{{ application_name}}/.env"
        src: "templates/clinical-report-templating.env.j2"
        owner: "{{ run_user }}"
        group: "{{ run_group }}"
        mode: 440

    - name: Include certs role
      include_role:
        name: certs

    - name: Create and start service
      become: yes
      become_user: "{{ run_user }}"
      community.docker.docker_compose_v2:
        project_src: "{{ deploy_root }}/{{ application_name }}"
        build: "always"
      register: output
    - name: Show results
      ansible.builtin.debug:
        var: output
