- name: Create deploy folder
  become: yes
  file:
    path: "{{ deploy_root }}/baserow"
    state: directory
    owner: "{{ run_user }}"
    group: "{{ run_group }}"
- name: Copy docker compose config to dest
  become: yes
  become_user: "{{ run_user }}"
  template:
    src: docker-compose.yaml.j2
    dest: "{{ deploy_root }}/baserow/docker-compose.yaml"
- name: Copy nginx custom conf to dest
  become: yes
  become_user: "{{ run_user }}"
  copy:
    src: nginx_custom.conf
    dest: "{{ deploy_root }}/baserow/"
- name: Create certs folder
  become: yes
  become_user: "{{ run_user }}"
  file:
    path: "{{ deploy_root }}/baserow/certs"
    state: directory
- name: Create and start service
  become: yes
  become_user: "{{ run_user }}"
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_root }}/baserow"
  register: output
- name: Show results
  ansible.builtin.debug:
    var: output
