- name: Ensure snap is installed
  become: true
  ansible.builtin.apt:
    name: snapd
    state: present
- name: Install certbot
  become: true
  community.general.snap:
    name: certbot
    classic: true
