baserow_token = "{{ baserow_token }}"
sams_user = "{{ sams_user }}"
sams_password = "{{ sams_password }}"
varfish_user = "{{ varfish_user }}"
varfish_password = "{{ varfish_password }}"
sodar_token = "{{ sodar_token }}"
varfish_token = "{{ varfish_token }}"
