- name: Install ACL
  become: true
  apt:
    name: 'acl'
    update_cache: yes
    cache_valid_time: '{{ 60 * 60 * 24 }}'
- name: Setup proxies
  become: true
  ansible.builtin.blockinfile:
    path: /etc/environment
    block: |
      http_proxy="http://proxy.charite.de:8080"
      https_proxy="http://proxy.charite.de:8080"
      no_proxy="bihealth.org,charite.de,laborberlin.intern"
- name: Install micromamba
  import_tasks: micromamba.yaml
- name: Install charite DNS check
  import_tasks: charite-dns.yaml
