- name: Create deploy folder
  become: yes
  file:
    path: "{{ deploy_root }}/freescout"
    state: directory
    owner: "{{ run_user }}"
    group: "{{ run_group }}"
- name: Copy docker compose config to dest
  become: yes
  become_user: "{{ run_user }}"
  template:
    src: docker-compose.yaml.j2
    dest: "{{ deploy_root }}/freescout/docker-compose.yaml"
- name: Copy nginx custom conf to dest
  become: yes
  become_user: "{{ run_user }}"
  copy:
    src: nginx_custom.conf
    dest: "{{ deploy_root }}/freescout/"
- name: Create certs folder
  become: yes
  become_user: "{{ run_user }}"
  file:
    path: "{{ deploy_root }}/freescout/certs"
    state: directory
- name: Create and start service
  become: yes
  become_user: "{{ run_user }}"
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_root }}/freescout"
  register: output
  environment:
    - FREESCOUT_ADMIN_EMAIL: "{{ freescout_admin_email }}"
    - FREESCOUT_ADMIN_PASS: "{{ freescout_admin_pass }}"
    - FREESCOUT_DB_ROOT_PASS: "{{ freescout_db_root_pass }}"
    - FREESCOUT_DB_PASS: "{{ freescout_db_pass }}"
- name: Show results
  ansible.builtin.debug:
    var: output
